{{- if or (.Values.shove.apns.certificate) (.Values.shove.apns.sandbox_certificate)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shove.fullname" . }}-apns
type: Opaque
data:
  {{- if .Values.shove.apns.certificate}}
  certificate: {{ .Values.shove.apns.certificate | b64enc | quote }}
  {{- end }}
  {{- if .Values.shove.apns.sandbox_certificate}}
  sandbox_certificate: {{ .Values.shove.apns.sandbox_certificate | b64enc | quote }}
  {{- end }}
{{- end }}