{{- if .Values.shove.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shove.fullname" . }}
  labels:
    {{- include "shove.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "shove.selectorLabels" . | nindent 4 }}
{{- end }}